# Change these first
owner: Trade-EC # Your GitHub organization or username, where this repository lives
repo: XMART-UPPTIME # The name of this repository

sites:
  - name: Orders Service Health Readiness
    url: https://api.artisn.desarrollo-redbrand.com/api/v4/health/orders/readiness
  - name: Orders Service Health Liveness
    url: https://api.artisn.desarrollo-redbrand.com/api/v4/health/orders/liveness

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.x-mart.io
  themeUrl: https://uptime.x-mart.io/custom-theme.css
  # baseUrl: /your-repo-name
  logoUrl: https://uptime.x-mart.io/logo.svg
  name: Upptime
  introTitle: "Xmart Uptime"
  introMessage: Check the availability of all Xmart services.
  navbar:
    - title: Status
      href: /
    - title: Docs
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

